### ISSUE TITLE
[Feature]: Custom medical bag for Polaris

### ISSUE THREAD

**Issue by swiftysmoon** [WitchFreya/SWSAddons#103]
### Discord Handle

Swiftysmoon

### Which type?

Medical Bag

### Recipient

Polaris

### Provide any additional details that may be helpful.

Wouldn't let me upload a .paa and you were super duper high, so I send in DM :3

**Comment by WitchFreya** [comment]
https://github.com/WitchFreya/SWSAddons/tree/103-design-add-armormedical-bag-config-for-polaris
