### ISSUE TITLE
[Feature]: Add medical bag for Carver

### ISSUE THREAD

**Issue by swiftysmoon** [WitchFreya/SWSAddons#146]
### Discord Handle

Swiftysmoon

### Which type?

Medical Bag

### Recipient

Carver

**Comment by WitchFreya** [comment]
https://github.com/WitchFreya/SWSAddons/tree/146-design-add-medical-bag-config-for-carver Branch done; file path for the bag is `addons\gear\data\Bag_Hardcase\carver_co.paa`.
