### ISSUE TITLE
[Bug]: ILCS Rucksack [Heavy] Not In Arsenal Unless Already Worn

### ISSUE THREAD

**Issue by LuckyOwl1364** [WitchFreya/SWSAddons#165]
### Discord Handle

Sunny / Spritz

### What happened, and what did you expect to happen?

When I open the SWS arsenal while my loadout does not include the ILCS Rucksack [Heavy], that backpack is not included in the list of backpacks. If I then put on a loadout with the backpack, it appears in the backpack list and stays there after taking it off until I exit the arsenal.

Video of bug: https://www.youtube.com/watch?v=FFFyiAMXK0k

(It isn't shown in the video, but the [Heavy] isn't available as an option on either of its two sisters)

### Attach your zipped RPT file

[Arma3_x64_2024-03-09_17-19-57.zip](https://github.com/WitchFreya/SWSAddons/files/14548188/Arma3_x64_2024-03-09_17-19-57.zip)

**Comment by WitchFreya** [comment]
That's interesting. Bet OPTRE bugged something. Will take a look!

**Comment by WitchFreya** [comment]
Ah, it's present, just in a weird spot.

https://github.com/WitchFreya/SWSAddons/assets/9843550/cbbb1279-83d6-4c40-9e64-8b745ab39020
