### ISSUE TITLE
[Feature]: Add custom ILCS bag for Manny

### ISSUE THREAD

**Issue by LupineMorningstar** [WitchFreya/SWSAddons#168]
### Discord Handle

Hound

### Which type?

Medical Bag

### Recipient

Manny

### Provide any additional details that may be helpful.

Manny requested his CLS bag be the ILCS-Medical variant! 

![IMG_5545](https://github.com/WitchFreya/SWSAddons/assets/156135231/f1d67607-822d-4b4a-b118-e7062433b116)

**Comment by WitchFreya** [comment]
https://github.com/WitchFreya/SWSAddons/blob/168-design-add-ilcs-bag-config-for-manny/addons/gear/data/bag_ilcs/manny_co.paa Have at it o7
