### ISSUE TITLE
Alternative Running: Disable running when in Zeus cam

### ISSUE THREAD

**Issue by WitchFreya** [WitchFreya/SWSAddons#17]
Double-tapping the keybinding when in Zeus cam will cause your body to start sprinting.

**Comment by EidolonForgery** [comment]
Whether or not I myself patch this, I'll leave a note for myself or someone else: 
We want to check if the display is open. `findDisplay` with the correct IDD, which you can find in a AIO Config or on the wiki.
The `curator` display is **312**, `map control` is **50**. If *both* of these, plus whatever other conditions we want, are off, then the bind should fire properly.

**Reference**
https://community.bistudio.com/wiki/ctrlShown (for map control)
https://community.bistudio.com/wiki/findDisplay 
https://community.bistudio.com/wiki/Arma_3:_IDD_List

**Comment by WitchFreya** [comment]
Fixed in main mod.
