### ISSUE TITLE
[Bug]: OPTRE lasers grey out loadouts

### ISSUE THREAD

**Issue by seamonstersapphic** [WitchFreya/SWSAddons#188]
### Discord Handle

Snare

### What happened, and what did you expect to happen?

When saving the Vector 343 binoculars into loadouts, it seems that the loadouts become greyed out as if missing something, even when using a full arsenal or when the binoculars are otherwise available to equip. I expected the loadout to appear normally in the loadout list.

### Attach your zipped RPT file

[Arma3_x64_2024-04-13_13-32-36.zip](https://github.com/WitchFreya/SWSAddons/files/14968264/Arma3_x64_2024-04-13_13-32-36.zip)

**Comment by WitchFreya** [comment]
This actually has nothing to do with the Vector but instead it's a bug with some of the OPTRE lasers not changing their state back. Should be an easy fix; thanks for catching.

**Comment by WitchFreya** [comment]
'Fixed' with #195

**Comment by WitchFreya** [comment]
Still present.  Annoyingly.
