### ISSUE TITLE
[Feature]: Add United Rebel Army

### ISSUE THREAD

**Issue by commanderkaya** [WitchFreya/SWSAddons#246]
### Discord Handle

commanderkaya

### Describe what sort of feature you are looking to have added

integrate the SWS United Rebel army custom faction into the main SWS modpack. 

note: the army is not finished and will require a few update versions once it has been added 

[SWS United Rebel Army.zip](https://github.com/user-attachments/files/15780786/SWS.United.Rebel.Army.zip)

**Comment by WitchFreya** [comment]
@commanderkaya I've put together a branch here: https://github.com/WitchFreya/SWSAddons/tree/246-add-sws-united-rebel-army

Your next steps should be the following:

1. Pull that branch to your local.
2. Open it up in VS Code and open a terminal.
3. Get hemtt
4. Depending on how you have hemtt installed, either do `hemtt.exe launch full acre alive` or `.\hemtt.exe launch full acre alive`.

When you get additional files from ALiVE with the updated versions, just change the files inside of `addons\units\o_ura`. However, **do not modify script_component.hpp and make sure that config.cpp always includes it at the top**, like so:
```hpp
// inside config.cpp
#include "script_component.hpp"
// rest of config.cpp file
```
