### ISSUE TITLE
[Design]: Add config for custom AR-0M37S

### ISSUE THREAD

**Issue by commanderkaya** [WitchFreya/SWSAddons#47]
### Discord Handle

Rabbit

### What type of config do you need?

Gear (CfgWeapons)

### What's the base class or path?

SWS_Weapon_AR0M37_GL

### What texture are you trying to change?

"\LM_OPCAN3.0\WEP\VAN\AR0M37_1.paa","\LM_OPCAN3.0\WEP\VAN\AR0M37_3.paa"

### Describe the nature of the changes you want to make and any other details.

Adding custom weapon texture option for Rabbit's TL gun

**Comment by WitchFreya** [comment]
Config has been added in the branch `freya/47-design-add-config-for-custom-ar-0m37s`.

Next steps:
1. Pull that branch.
2. Replace `rabbit_co.paa` & `rabbit_underbarrel_co.paa` with your files.
3. Commit them to the branch and push. Your commit message can be something like `feat(weapons): Added texture for Rabbit's gun`
4. Click on Pull Requests up top, you should see a popup that says 'Compare and pull request'.
5. When it asks you for a title, use something like `feat(weapons): Custom AR-0M37S for Rabbit`.
6. Hit Create Pull Request.

Feel free to ask me if you need any help; there should be some instructions in the wiki for how to branch and such but it may be confusing for the first time doing it and I'll probably write up something on it properly soon.
