### ISSUE TITLE
[Bug]: DMNS (19th) Pelican unable to load the SWS Viper 

### ISSUE THREAD

**Issue by LupineMorningstar** [WitchFreya/SWSAddons#54]
### Discord Handle

Hound

### What happened, and what did you expect to happen?

We've discovered that the 19th's Pelican is unable to load the SWS Viper / Cougar via Maglock. "This vehicle is not designed to be maglocked" 

I presume that we should be able reference our existing patch to the base pelicans to make the 19th's pelican able to mag-lock the viper/cougar

### Attach your zipped RPT file

N/A

**Comment by WitchFreya** [comment]
@EidolonForgery I'll let you fix this, I hate looking at this code and I'd rather spend my energy rewriting it into something practical than figuring this out.

When you test it, please make sure it doesn't explode on unload. 👍🏻
