### ISSUE TITLE
[Feature]: Add Rucksacks

### ISSUE THREAD

**Issue by LupineMorningstar** [WitchFreya/SWSAddons#79]
### Discord Handle

Hound

### What type of config do you need?

Vehicle/UAV/Unit or similar (CfgVehicles)

### What's the base class or path?

configFile >> "CfgVehicles" >> "OPTRE_ILCS_Rucksack_Black"

### What texture are you trying to change?

@Operation TREBUCHET\addons\OPTRE_Weapons\Backpacks\data\ruck_black_CO.paa

### Describe the nature of the changes you want to make and any other details.

I want to make a SWS version of the ILCS bags + A funny Hound-specific bag

**Comment by WitchFreya** [comment]
https://github.com/WitchFreya/SWSAddons/tree/79-design-add-config-ilcs-backpack-retexture

Let me know if you need any of the rvmat/other files to modify as well, or if you need variations on the biofoam/softpacks.
