### ISSUE TITLE
[Feature]: New LR pack S/PRC-810

### ISSUE THREAD

**Issue by LupineMorningstar** [WitchFreya/SWSAddons#80]
### Discord Handle

Hound

### What type of config do you need?

Vehicle/UAV/Unit or similar (CfgVehicles)

### What's the base class or path?

configFile >> "CfgVehicles" >> "19thANPRC419"

### What texture are you trying to change?

I can't actually find this one D: 

### Describe the nature of the changes you want to make and any other details.

I want to make an SWS version of this bag + a fun little Hound specific texture for it

**Comment by WitchFreya** [comment]
I'll take care of this tomorrow.

**Comment by WitchFreya** [comment]
Check this branch: https://github.com/WitchFreya/SWSAddons/tree/freya/80-design-add-config-anprc-419
It should have the configs you need under `addons\gear\bag_s_prc_810` and the associated gear folder. I've made variants for `bag_hard_hound_co.paa` and `radio_hound_co.paa`; if you need additional files or configs let me know.

`bag_soft.paa` is hidden in the existing configs, as it's not visibly a radio.

**Comment by WitchFreya** [comment]
Closing this out for now, lmk if you need it again.
