### ISSUE TITLE
[Bug]: Hornet radar signature is oversized

### ISSUE THREAD

**Issue by WitchFreya** [WitchFreya/SWSAddons#85]
### Discord Handle

webwitch

### What happened, and what did you expect to happen?

The Hornet's radar signature is bigger than a Blackfish. Let's fix that.

### Attach your zipped RPT file

N/A

**Comment by EidolonForgery** [comment]
I may rebalance *all* of the radar sigs for OPTRE: They're all kinda fucked.

**Comment by Fluxom-Art** [comment]
OTOMH the base Pelican model and the Sparrowhawks have the same issue, though I haven't double checked them recently and they're less of a concern to me given that those both have more functional alternatives in most situations.
