### ISSUE TITLE
[Investigate]: Uptick in AI eagerness to utilize SPNKRs

### ISSUE THREAD

**Issue by WitchFreya** [WitchFreya/SWSAddons#90]
There's been a recent increase in AI's desire to utterly delete things with manpads; I'd like to see what's up with that.

Notable symptoms are AI walking around near players with the SPNKR held out instead of their rifle; one such culprit it was seen from is `O_CLA_Rifleperson_02`.

We're currently uncertain if they're actively firing these are players or just carrying them more readily to deal with armor; it could also be a symptom of us deploying armor/air assets more often that we're just now noticing.

**Comment by EidolonForgery** [comment]
Short term analysis (AI v. AI) suggests that this is due to armor. Testing a prolonged engagement with BLU AI both in cover and out had mass amounts of RIflePerson 2s never activating their launcher.

**Comment by WitchFreya** [comment]
Gotcha. Won't worry about it then.
