### ISSUE TITLE
[Feature]: Custom armor for Spritz

### ISSUE THREAD

**Issue by LupineMorningstar** [WitchFreya/SWSAddons#97]
### Discord Handle

Hound

### What type of config do you need?

Vehicle/UAV/Unit or similar (CfgVehicles)

### What's the base class or path?

NA

### What texture are you trying to change?

NA?

### Describe the nature of the changes you want to make and any other details.

Adding new custom armor for spritz

**Comment by WitchFreya** [comment]
https://github.com/WitchFreya/SWSAddons/tree/97-design-add-config-for-spritz
