### ISSUE TITLE
[Investigate]: Git LFS for some of the textures.

### ISSUE THREAD

**Issue by WitchFreya** [WitchFreya/SWSAddons#99]
Our textures are pretty large in here; we may wanna try out Git LFS or compress them somehow. Will require some research.

**Comment by EidolonForgery** [comment]
As far as compression of the textures proper goes, I've been looking around. While "PAA" doesn't compress very well, apparently we're actually using DXT1 'mode'? I don't understand it well, but by asking around on some arma discord servers and looking at the wiki page on PAA files, I uncovered an interesting [blog post](https://www.sjbrown.co.uk/posts/dxt-compression-techniques/) and the linked [library](https://github.com/svn2github/libsquish) designed to compress the DXT files further.
